// Generated by CoffeeScript 1.6.1
(function() {

  define(['backbone', 'underscore'], function(Backbone, _) {
    var Component;
    return Component = (function() {

      function Component() {
        _.extend(this, Backbone.Events);
      }

      return Component;

    })();
  });

}).call(this);
