// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var Point;
    return Point = (function() {

      function Point(x, y) {
        this.x = x;
        this.y = y;
      }

      Point.prototype.set = function(x, y) {
        this.x = x;
        this.y = y;
      };

      return Point;

    })();
  });

}).call(this);
