// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var Rectangle;
    return Rectangle = (function() {

      function Rectangle(x, y, w, h) {
        this.x = x;
        this.y = y;
        this.w = w;
        this.h = h;
      }

      Object.defineProperties(Rectangle.prototype, {
        x1: {
          get: function() {
            return this.x;
          },
          set: function(x) {
            this.x = x;
          }
        },
        x2: {
          get: function() {
            return this.x + this.w;
          },
          set: function(x2) {
            return this.w = x2 - this.x;
          }
        },
        y1: {
          get: function() {
            return this.y;
          },
          set: function(y) {
            this.y = y;
          }
        },
        y2: {
          get: function() {
            return this.y + this.h;
          },
          set: function(y2) {
            return this.w = y2 - this.y;
          }
        }
      });

      return Rectangle;

    })();
  });

}).call(this);
