// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var Viewport;
    return Viewport = (function() {

      function Viewport(src, dest) {
        this.src = src;
        this.dest = dest;
      }

      Viewport.prototype.srcToDest = function(inPt, outPt) {
        outPt.x = (inPt.x - this.src.x) / this.src.w * this.dest.w + this.dest.x;
        return outPt.y = (inPt.y - this.src.y) / this.src.h * this.dest.h + this.dest.y;
      };

      Viewport.prototype.destToSrc = function(inPt, outPt) {
        outPt.x = (inPt.x - this.dest.x) / this.dest.w * this.src.w + this.src.x;
        return outPt.y = (inPt.y - this.dest.y) / this.dest.h * this.src.h + this.src.y;
      };

      return Viewport;

    })();
  });

}).call(this);
