/* CVS $Id: $ */
package org.ivpr.udc.sql; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from label.owl 
 * @author Auto-generated by schemagen on 30 Jul 2010 12:11 
 */
public class LABEL {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/net/vocab/2004/03/label#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>En relation mellem en term og dens inverses navn i flertalsformA relation 
     *  between a term and the label of its inverse in literal plural form</p>
     */
    public static final AnnotationProperty inversePlural = m_model.createAnnotationProperty( "http://purl.org/net/vocab/2004/03/label#inversePlural" );
    
    /** <p>A relation between a term and the label of its inverse in literal singular 
     *  formEn relation mellem en term og dens inverses navn i entalsform</p>
     */
    public static final AnnotationProperty inverseSingular = m_model.createAnnotationProperty( "http://purl.org/net/vocab/2004/03/label#inverseSingular" );
    
    /** <p>Una relación entre un término y su etiqueta en forma pluralEn relation mellem 
     *  en term og dens navn i flertalsformA relation between a term and its label 
     *  in literal plural form</p>
     */
    public static final AnnotationProperty plural = m_model.createAnnotationProperty( "http://purl.org/net/vocab/2004/03/label#plural" );
    
    /** <p>Una relación entre un término y su etiqueta en forma singularEn relation mellem 
     *  en term og dens navn i entalsformA relation between a term and its label in 
     *  literal singular form</p>
     */
    public static final AnnotationProperty singular = m_model.createAnnotationProperty( "http://purl.org/net/vocab/2004/03/label#singular" );
    
}
